---
title: "smoke free dividend results"
date: "`r format(Sys.Date(), format = '%B %Y')`"
output:
  bookdown::word_document2:
    toc: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

suppressPackageStartupMessages(library(here))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(cowplot))
suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(flextable))
suppressPackageStartupMessages(library(magrittr))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(smkfreediv))

```

```{r data_prep, include = FALSE}

#### for correlation plots 
div_la <- readRDS("intermediate_data/results_local_authority.rds")

geog <- merge(smkfreediv::la_gor_lookup, smkfreediv::localauthorities, by = c("LAcode","LAname"))
geog <- unique(geog[,c("GORcode",  "GORname",  "UTLAcode", "UTLAname")])

plot_data <- merge(div_la, geog, by = "UTLAcode")

############
## HEAT MAPS

# merge UTLA level variables to U/L mapping data

data_mapping_merge <- merge(div_la, smkfreediv::localauthorities, by = c("UTLAcode","UTLAname"))

# merge all to the shapefile

shape <- readRDS("input_data/shapefile_la.rds")

map_data <- merge(data_mapping_merge, shape, by.x = "LAcode", by.y = "id", all.y = F)
map_data <- arrange(map_data,order)
```


```{r inc_smkprev, echo = FALSE, warning = FALSE, message = FALSE,  fig.asp = 0.8, fig.width = 6}

ggplot(plot_data) +
  aes(x = income/1000, y = smk_prev) +
  geom_point() +
  geom_smooth(method='lm', se = F, color='turquoise4', linetype = 5) +
  theme_minimal() +
  labs(x = "Average Income (£000s)",
       y = "Smoking Prevalence (%)",
       title = "",
       color = "Region") +
  scale_y_continuous(breaks = seq(6,26,2), minor_breaks = NULL) +
  scale_x_continuous(breaks = seq(5,45,5), minor_breaks = NULL)

```


```{r inc_smkprev_byregion, echo = FALSE, warning = FALSE, message = FALSE, fig.asp = 0.8, fig.width = 6}

ggplot(plot_data) +
  aes(x = income/1000, y = smk_prev , color = GORname) +
  geom_point() +
  geom_smooth(method='loess', se = F, color='black', linetype = 5) +
  theme_minimal() +
  labs(x = "Average Income (£000s)",
       y = "Smoking Prevalence (%)",
       title = "",
       color = "Region") +
  scale_y_continuous(breaks = seq(6,26,2), minor_breaks = NULL) +
  scale_x_continuous(breaks = seq(5,45,5), minor_breaks = NULL) +
  scale_colour_viridis_d()

```


```{r inc_smkprev_byregion_reg, echo = FALSE, warning = FALSE, message = FALSE, fig.asp = 0.8, fig.width = 6}

ggplot(plot_data) +
  aes(x = income/1000, y = smk_prev , color = GORname, linetype = GORname) +
  geom_point() +
  geom_smooth(method='lm', se = F, color='black') +
  theme_minimal() +
  labs(x = "Average Income (£000s)",
       y = "Smoking Prevalence (%)",
       title = "",
       color = "Region",
       linetype = "Region") +
  scale_y_continuous(breaks = seq(6,26,2), minor_breaks = NULL) +
  scale_x_continuous(breaks = seq(5,45,5), minor_breaks = NULL) +
  scale_colour_viridis_d()

```


```{r , echo = FALSE, warning = FALSE, message = FALSE, fig.asp = 0.8, fig.width = 6}
## plot mean weekly spend (upshifted) against income

ggplot(plot_data) +
  aes(x = income/1000, y = mean_week_spend_up) +
  geom_point() +
  geom_smooth(method='lm', se = F, color='turquoise4', linetype = 5) +
  theme_minimal() +
  labs(x = "Average Income (£000s)",
       y = "Mean Weekly Spend (£)",
       title = "",
       color = "Region") +
  scale_y_continuous(breaks = seq(20,70,5), minor_breaks = NULL) +
  scale_x_continuous(breaks = seq(5,45,5), minor_breaks = NULL)
```

```{r , echo = FALSE, warning = FALSE, message = FALSE, fig.asp = 0.8, fig.width = 6}
## plot spend % of income (upshifted) against income

ggplot(plot_data) +
  aes(x = income/1000, y = spend_prop_up*100) +
  geom_point() +
  geom_smooth(method='lm', se = F, color='turquoise4', linetype = 5) +
  theme_minimal() +
  labs(x = "Average Income (£000s)",
       y = "Mean Spend as % of Disposable Income",
       title = "",
       color = "Region") +
  scale_y_continuous(breaks = seq(0,100,1), minor_breaks = NULL) +
  scale_x_continuous(breaks = seq(5,45,5), minor_breaks = NULL)
```

```{r , echo = FALSE, warning = FALSE, message = FALSE, fig.asp = 0.8, fig.width = 6}
### plot heat map by smoking prevalence 

ggplot(data = map_data) +
  aes(x = long,
      y = lat,
      group = group,
      fill = cut(smk_prev,
                 breaks = c(0,10,12,14,16,18,20,100),
                 labels = c("Under 10%",
                            "10-12%",
                            "12-14%",
                            "14-16%",
                            "16-18%",
                            "18-20%",
                            "Over 20%"))) +
  geom_polygon() + coord_equal() + theme_void() +
  labs(fill = "Smoking Prevalence") +
  scale_fill_viridis_d()
```

```{r , echo = FALSE, warning = FALSE, message = FALSE, fig.asp = 0.8, fig.width = 6}
### plot heat map by expenditure 

ggplot(data = map_data) +
  aes(x = long,
      y = lat,
      group = group,
      fill = cut(mean_week_spend,
                 breaks = c(0,20,22,25,28,30,35,100),
                 labels = c("Under £20",
                            "£20 - £22",
                            "£22 - £25",
                            "£25 - £28",
                            "£28 - £30",
                            "£30 - £35",
                            "Over £35"))) +
  geom_polygon() + coord_equal() + theme_void() +
  labs(fill = "Mean Weekly Spend") +
  scale_fill_viridis_d()

```
